name: template
description: Template - Storeware by WBAGestão

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2021.11.10

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.1.4
  provider: ^6.0.0
  universal_io: ^2.0.4
  uuid: ^3.0.4
  encrypt: ^5.0.0

  desktop_window: ^0.4.0

  console:
    git:
      url: https://github.com/amarildolacerda/console.git

  #    path: ../../estoque/console

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  charts_flutter: ^0.11.0
  shimmer: ^2.0.0
  #line_icons: ^2.0.1

  #desktoasts: ^0.0.2

dependency_overrides:
  pointycastle: ^3.2.0-rc0
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf

  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: printing
  #pdf: ^3.1.0
  #intl: ^0.17.0
  #get: ^4.0.0-nullsafety.2
  #flutter_cache_manager: ^3.0.0-nullsafety.1
  #image: ^3.0.1
  #uuid: ^3.0.0
  crypto: ^3.0.1
  dio: ^4.0.0
  #image_picker: ^0.7.2+1
  provider: ^6.0.0
  encrypt: ^5.0.1
  args: ^2.0.0
  convert: ^3.0.0
  timezone: ^0.8.0
  firebase_messaging: ^10.0.0

  controls_web:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_web

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  msix: ^2.1.3

  wave: any
  controls_firebase:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_firebase

  controls_dash:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_dash

flutter:
  #uses-material-design: true
  assets:
    - assets/
    - assets/nav/

msix_config:
  #https://sahajrana.medium.com/how-to-generate-a-pfx-certificate-for-flutter-windows-msix-lib-a860cdcebb8
  display_name: Storeware Gestor
  publisher_display_name: WBA Gestão - Storeware
  identity_name: com.storeware.gestor
  msix_version: 2021.9.18.0
  certificate_path: C:\Flutter\miniapps\wbagestao.pfx
  certificate_password: 1234
  publisher: CN=wbagestao, O=wbagestao, S=SaoPaulo, C=BR
  logo_path: .\web\favicon.png
  start_menu_icon_path: .\web\favicon.png
  tile_icon_path: .\web\favicon.png
  #vs_generated_images_folder_path: .\Images
  icons_background_color: transparent
  architecture: x64
  capabilities: "internetClient,location,microphone,webcam"
