name: controls_firebase_macos
description: A new Flutter package project.
version: 0.0.3
author:
homepage: https://wbagestao.com
#publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

controls_firebase_platform_interface:
  git:
    url: https://github.com/amarildolacerda/flutter_dart.git
    path: controls_firebase/controls_firebase_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
