name: controls_firebase_platform_interface
description: A new Flutter package project.
version: 2021.06.16
author:
homepage: tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
