name: controls_firebase_platform_interface
description: A new Flutter package project.
version: 0.0.7
author:
homepage: tireideletra.com.br

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
