name: controls_firebase_platform_android
description: Firebase interface WEB, ANDROID e WINDOWS
version: 2022.01.20
publish_to: none

platform:
  android:
  web:
  windows:
  linux:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: any #^2.0.1
  flutter_cache_manager: any # ^3.0.0-nullsafety.1
  google_sign_in: any #^5.0.0
  firebase_auth: any #^1.0.1
  firebase_core: any #^1.0.1
  firebase_storage: any #^8.0.0
  firebase_messaging: any #^10.0.7
  cloud_firestore: any #^1.0.1
  flutter_local_notifications: ^9.2.0
  

  controls_firebase_platform_interface:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_firebase/controls_firebase_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
