name: controls_firebase_platform_android
description: A new Flutter package project.
version: 2021.03.14
author:
homepage: https://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.0
  flutter_cache_manager: ^3.0.0-nullsafety.1
  google_sign_in: ^5.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_messaging: ^9.0.0
  cloud_firestore: ^1.0.1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  

  controls_firebase_platform_interface:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_firebase/controls_firebase_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
