name: comum
description: A new Flutter package project.
version: 2021.03.14

homepage: http://tireideletra.com.br
publish_to: none


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  controls_web:
    #git:
      #url: https://github.com/amarildolacerda/flutter_dart.git
      path: ../controls_web
  controls_data:
    #git:
      #url: https://github.com/amarildolacerda/flutter_dart.git
      path: ../controls_data
  controls_extensions:
    #git:
      #url: https://github.com/amarildolacerda/flutter_dart.git
      path: ../controls_extensions
  #controls_firebase:
  #  git:
  #    url: https://github.com/amarildolacerda/flutter_dart.git
  #    path: controls_firebase
  controls_dash:
    #git:
     # url: https://github.com/amarildolacerda/flutter_dart.git
      path: ../controls_dash
  get: ^4.0.0-nullsafety.2   

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  