name: comum
description: Storeware package de uso geral.
version: 22.08.10+1

homepage: http://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  controls_web:
    path: ../controls_web
  controls_data:
    path: ../controls_data
  controls_extensions:
    path: ../controls_extensions
  #controls_firebase:
  #  git:
  #    url: https://github.com/amarildolacerda/flutter_storeware.git
  #    path: controls_firebase
  controls_dash:
    path: ../controls_dash
  models:
    path: ../models
  get:
  web_socket_channel:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
