name: controls_dash
description: Adds for charts_flutter
version: 2021.08.18
homepage: http://tireideletra.com.br
publish_to: none


environment:
  sdk: ">=2.12.0 <3.0.0"
  # aguardando nullsafety para o charts_flutter.

dependencies:
  flutter:
    sdk: flutter

  charts_flutter: ^0.11.0 
  #   git:
  #    url: https://github.com/simpleclub-extended/charts
  #    path: charts_flutter
  #    ref: intl-git
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  