name: control_data_platform_windows
description: A new Flutter package project.
version: 2021.11.10
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  control_data_platform_interface:
    path: ../control_data_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  