name: html_container
description: A new Flutter package project.
version: 0.0.1
homepage: http://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: html_container_web
      android:
        default_package: html_container_io
      windows:
        default_package: html_container_io
      ios:
        default_package: html_container_io

dependencies:
  flutter:
    sdk: flutter

  html_container_web:
    #git:
    #  url: https://github.com/amarildolacerda/flutter_dart.git
      path: ./html_container_web

  html_container_io:
    #git:
     # url: https://github.com/amarildolacerda/flutter_dart.git
      path: ./html_container_io

dev_dependencies:
  flutter_test:
    sdk: flutter
