name: control_data_platform_android
description: A new Flutter package project.
version: 22.08.10+1
homepage: https://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  control_data_platform_interface:
    path: ../control_data_platform_interface
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
