name: control_data_platform_android
description: A new Flutter package project.
version: 2021.03.17
author: Amarildo Lacerda
homepage: https://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  control_data_platform_interface:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_data/control_data_platform_interface
  shared_preferences: ^2.0.5 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  