name: controls_firebase
description: A new Flutter package project.
version: 2021.03.14
author:
homepage: http://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: controls_firebase_platform_web
      linux:
        default_package: controls_firebase_linux
      android:
        default_package: controls_firebase_platform_android
      windows:
        default_package: controls_firebase_windows
      macos:
        default_package: controls_firebase_linux

      ios:
        default_package: controls_firebase_platform_android

dependencies:
  flutter:
    sdk: flutter
  controls_data:
    #git:
    #  url: https://github.com/amarildolacerda/flutter_dart.git
      path: ../controls_data

  controls_firebase_platform_web:
    #git:
    #  url: https://github.com/amarildolacerda/flutter_dart.git
      path: ./controls_firebase_platform_web
  controls_firebase_platform_android:
    #git:
    #  url: https://github.com/amarildolacerda/flutter_dart.git
      path: ./controls_firebase_platform_android

  controls_firebase_linux:
    #git:
      #url: https://github.com/amarildolacerda/flutter_dart.git
      path: ./controls_firebase_linux

  #controls_firebase_macos:
  #  git:
  #    url: https://github.com/amarildolacerda/flutter_dart.git
  #    path: controls_firebase/controls_firebase_macos

  controls_firebase_windows:
    #git:
      #url: https://github.com/amarildolacerda/flutter_dart.git
      path: ./controls_firebase_windows

  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
