name: controls_firebase
description: A new Flutter package project.
version: 2021.10.04
homepage: http://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: controls_firebase_platform_web
      android:
        default_package: controls_firebase_platform_android
      ios:
        default_package: controls_firebase_platform_android

dependencies:
  flutter:
    sdk: flutter
  universal_html:  ^2.0.8
  controls_data:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_data

  controls_firebase_platform_web:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_firebase/controls_firebase_platform_web
  controls_firebase_platform_android:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_firebase/controls_firebase_platform_android

  
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
