name: controls_firebase
description: FirebaseInterface.
version: 2022.08.03
homepage: http://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html:
  controls_data:
    path: ../controls_data

  controls_firebase_platform_interface:
    path: ./controls_firebase_platform_interface

  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  google_sign_in: ^5.4.0
  firebase_auth: ^4.2.5
  flutter_local_notifications: ^13.0.0

dependency_overrides:
  platform: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
