name: controls_firebase
description: FirebaseInterface.
version: 2022.08.03
homepage: http://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html:
  controls_data:
    path: ../controls_data

  controls_firebase_platform_interface:
    path: ./controls_firebase_platform_interface

  cloud_firestore: ^3.4.3
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  firebase_messaging: ^12.0.1
  google_sign_in: ^5.4.0
  firebase_auth: ^3.6.2
  flutter_local_notifications: ^9.7.0

dependency_overrides:
  platform: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
