name: controls_firebase
description: A new Flutter package project.
version: 0.0.1
author:
homepage: http://tireideletra.com.br

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: controls_firebase_platform_web
      android:
        default_package: controls_firebase_platform_android
      windows:
        default_package: controls_firebase_platform_windows
      ios:
        default_package: controls_firebase_platform_android

dependencies:
  flutter:
    sdk: flutter
  controls_data:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_data

  controls_firebase_platform_web:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_data/controls_firebase_platform_web

  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
