name: controls_image
description: A new Flutter package project.
version: 0.0.1
author:
homepage: https://tireideletra.com.br

environment:
  sdk: ">=2.1.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: controls_image_web
      android:
        default_package: controls_image_android
      windows:
        default_package: controls_image_android
      ios:
        default_package: controls_image_android

dependencies:
  flutter:
    sdk: flutter

  universal_io: ^2.0.0  
  controls_image_web:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_image/controls_image_web
  controls_image_android:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_image/controls_image_android

dev_dependencies:
  flutter_test:
    sdk: flutter
