name: controls_image
description: A new Flutter package project.
version: 2021.09.27
homepage: https://tireideletra.com.br
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: controls_image_web
      android:
        default_package: controls_image_android
      windows:
        default_package: controls_image_android
      ios:
        default_package: controls_image_android

dependencies:
  flutter:
    sdk: flutter

  universal_io: any 
  image_picker: any 
  extended_image: any
  photofilters: any
  image_editor: any
  controls_image_web:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_image/controls_image_web
  controls_image_android:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_image/controls_image_android

  controls_web:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_web  

dev_dependencies:
  flutter_test:
    sdk: flutter
