name: controls_data
description: A new Flutter package project.
version: 0.0.8
author:
homepage: https://tireideletra.com.br

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: control_data_platform_web
      linux:
        default_package: control_data_platform_android
      android:
        default_package: control_data_platform_android
      windows:
        default_package: control_data_platform_android
      ios:
        default_package: control_data_platform_android

dependencies:
  #shared_preferences: ^0.5.6+1
  flutter:
    sdk: flutter
  intl:
  #universal_html:
  #http:
  dio:

  control_data_platform_web:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_data/control_data_platform_web

  control_data_platform_android:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_data/control_data_platform_android

  control_data_platform_windows:
    git:
      url: https://github.com/amarildolacerda/flutter_dart.git
      path: controls_data/control_data_platform_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
