name: controls_data
description: A new Flutter package project.
version: 0.0.5
author:
homepage: http://tireideletra.com.br

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.6+1
  flutter:
    sdk: flutter
  intl:
  universal_html:
  #http:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: