name: controls_data
description: Storeware data package.
version: 2021.10.11
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: control_data_platform_web
      linux:
        default_package: control_data_platform_android
      android:
        default_package: control_data_platform_android
      windows:
        default_package: control_data_platform_windows
      ios:
        default_package: control_data_platform_android

dependencies:
  #shared_preferences: ^0.5.6+1
  flutter:
    sdk: flutter
  intl:
  #universal_html:
  #http:
  
  dio: any
  connectivity: #^3.0.2
  uuid: #^3.0.1
  universal_platform: any
  universal_io: any
  flutter_cache_manager: any
  pdf: any
  printing: any
  date_format: #^2.0.2

  control_data_platform_web:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_data/control_data_platform_web

  control_data_platform_android:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_data/control_data_platform_android

  control_data_platform_windows:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_data/control_data_platform_windows

  controls_extensions:
   git:
     url: https://github.com/amarildolacerda/flutter_storeware.git
     path: controls_extensions
  #controls_web:
   #git:
     #url: https://github.com/amarildolacerda/flutter_dart.git
  #   path: ../controls_web

dev_dependencies:
  flutter_test:
    sdk: flutter
