name: models
description: Model Package.
version: 22.04.23+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # http:
  dio:

  uuid:

  #console:
  #  git:
  #    url: https://github.com/amarildolacerda/console.git
  #path: controls_web

  controls_web:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_web
  controls_data:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_data

  controls_extensions:
    git:
      url: https://github.com/amarildolacerda/flutter_storeware.git
      path: controls_extensions

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
